pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
        stage('complete') {
            steps {
                echo 'App build completed'
            }
        }
    }
}
