pipeline {
    agent any
    stages {
        stage('Build') {
            withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                steps {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                steps {
                    sh 'mvn test'
                }
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deliver') {
            withEnv(['PATH+MAVEN_HOME=/opt/maven/bin']) {
                steps {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
